// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtiWmxOcFRnF8I6C7_GSRy_tqnSXl6Bzw',
    appId: '1:77605466678:web:4efad4f6933534937f9e97',
    messagingSenderId: '77605466678',
    projectId: 'chat-app-34708',
    authDomain: 'chat-app-34708.firebaseapp.com',
    storageBucket: 'chat-app-34708.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMcJB37a78Jh577J-k4AaSUzWRq7XyPAQ',
    appId: '1:77605466678:android:1c1f2c80faf318437f9e97',
    messagingSenderId: '77605466678',
    projectId: 'chat-app-34708',
    storageBucket: 'chat-app-34708.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTv4rnzRyc7n3zP-Raq0L-aISWALgDHw4',
    appId: '1:77605466678:ios:a1947bbe71f812047f9e97',
    messagingSenderId: '77605466678',
    projectId: 'chat-app-34708',
    storageBucket: 'chat-app-34708.appspot.com',
    iosBundleId: 'com.example.chatapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTv4rnzRyc7n3zP-Raq0L-aISWALgDHw4',
    appId: '1:77605466678:ios:a1947bbe71f812047f9e97',
    messagingSenderId: '77605466678',
    projectId: 'chat-app-34708',
    storageBucket: 'chat-app-34708.appspot.com',
    iosBundleId: 'com.example.chatapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtiWmxOcFRnF8I6C7_GSRy_tqnSXl6Bzw',
    appId: '1:77605466678:web:642fee822328dfdc7f9e97',
    messagingSenderId: '77605466678',
    projectId: 'chat-app-34708',
    authDomain: 'chat-app-34708.firebaseapp.com',
    storageBucket: 'chat-app-34708.appspot.com',
  );

}